AWSTemplateFormatVersion: "2010-09-09"
Description: S3 Bucket

Parameters:
  S3BucketName:
    Type: String
    Default: ${{env:S3_BUCKET_NAME}}

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: S3BucketName
      AccessControl: Private

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: WebsiteBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action: s3:GetObject
            Resource:
              Fn::Sub: ${Bucket.Arn}/*
            Principal: "*"
