name: Scheduled Update
on:
  push:
    branches:
      - master
      - main
  schedule:
    - cron: '0 0 * * *'
jobs:
  update:
    name: "Update"
    runs-on: ubuntu-18.04
    if: github.repository.full_name != 'azu/mytweets'
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install
        run: yarn install
      - name: Update
        run: |
          yarn fetch-tweets
          yarn upload-tweets
        env:
          S3_AWS_ACCESS_KEY_ID: ${{ secrets.S3_AWS_ACCESS_KEY_ID }}
          S3_AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          TWITTER_APP_KEY: ${{ secrets.TWITTER_APP_KEY }}
          TWITTER_APP_SECRET: ${{ secrets.TWITTER_APP_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
      - name: Commit
        uses: EndBug/add-and-commit@v7
        with:
          message: "Update Data"
          add: 'data'
          push: true
